name: Run Pester tests on Pull Requests

on:
  pull_request:

jobs:
  build-image:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 2
        ref: ${{ github.event.pull_request.head.ref }}
    - name: test module
      id: test_module
      uses: zyborg/pester-tests-report@v1.5.0
      with:
        include_paths: .
        # exclude_paths: tests/powershell1,tests/powershell2
        exclude_tags: skip_ci
        report_name: module_tests
        report_title: Pester Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        EIDATPESTERCERTIFICATEPFX: ${{ secrets.EIDATPESTERCERTIFICATEPFX }}
        EIDATPESTERCERTIFICATEPFXPASSWORD: ${{ secrets.EIDATPESTERCERTIFICATEPFXPASSWORD }}
        EIDATPESTERCLIENTSECRET: ${{ secrets.EIDATPESTERCLIENTSECRET }}
        EIDATPESTERPASSWORD: ${{ secrets.EIDATPESTERPASSWORD }}
    - name: dump test results
      shell: pwsh
      run: |
        Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
        Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
        Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'