name: Publish Module to internal ACR
permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Publish Module to internal ACR
        shell: pwsh
        run: |
          $managedserviceclientid = "5560e545-ab37-4d76-ac15-3d35b641b2ec"
          Install-Module Az.Accounts
          Connect-AzAccount -ServicePrincipal -Tenant "237098ae-0798-4cf9-a3a5-208374d2dcfd" -ApplicationId $managedserviceclientid -FederatedToken $$ACTIONS_ID_TOKEN_REQUEST_TOKEN -Verbose
          Register-PSResourceRepository -Name FortytwoInternal -Uri "https://fortytwointernal.azurecr.io/"

          $psd1 = Get-ChildItem -Recurse -Include *.psd1
          $RequiredModules = [ScriptBlock]::Create((Get-Content -Raw $psd1.FullName)).Invoke().RequiredModules
          if($RequiredModules) {
            $RequiredModules | ForEach-Object {
              Write-Host "Installing required module - $($_)"
              Install-PSResource -Name $_ -Force -Confirm:$false -Repository FortytwoInternal
            }
          }

          $psd1 |
          ForEach-Object {
            Test-ModuleManifest $_.FullName

            $ModulePath = Split-Path -Parent $_.FullName
            $ModuleName = $_.BaseName
            Write-Host "Publishing module $ModuleName"
            publish-PSResource -Path $ModulePath -Repository FortytwoInternal
          }
